### ISSUE TITLE
Why Use Universal2 instead of aarch64?

### ISSUE THREAD

**Issue by after-ephemera** [messense/crfs-rs#13]
This is sort of a meta issue. I arrived here from the [maturin-action examples](https://github.com/messense/maturin-action) and I noticed that crfs builds [both an x86 and a universal2 binary](https://github.com/messense/crfs-rs/blob/main/.github/workflows/Python.yml#L31.). Is there a reason for doing both and not just universal2 or x86 and aarch64?

**Comment by messense** [comment]
x86_64 to support older macOS, universal2 is good for small sized library and on Apple Silicon Mac it supports switching to x86 via `arch -x86_64 python` when you need to use x86_64 for some reasons, but if it grows too big, use aarch64 might be better.
